export const languages = [
  { language: 'plaintext', label: 'Plain text' },
  { language: 'html', label: 'HTML' },
  { language: 'css', label: 'CSS' },
  { language: 'javascript', label: 'JavaScript' },
  { language: 'typescript', label: 'TypeScript' },
  { language: 'jsx', label: 'Javascript React' },
  { language: 'tsx', label: 'Typescript React' },
  { language: 'php', label: 'PHP' },
  { language: 'python', label: 'Python' },
  { language: 'bash', label: 'Bash' },
  { language: 'c', label: 'C' },
  { language: 'cpp', label: 'C++' },
  { language: 'java', label: 'Java' },
  { language: 'go', label: 'Go' },
  { language: 'sql', label: 'SQL' },
  { language: 'json', label: 'JSON' },
  { language: 'yaml', label: 'YAML' },
  { language: 'xml', label: 'XML' },
  { language: 'markdown', label: 'Markdown' },
  { language: 'mdx', label: 'Markdown React' },
  { language: 'dockerfile', label: 'Dockerfile' },
]

